Feature/log
extreal-dev/Extreal.Core.Logging pull request #2
Opened 2022-10-12 08:50 UTC by sus-taguchi-t

#1 

# Describe Your Changes (なんの変更を加えましたか?)

- フォーマッタを導入した
- 静的解析を導入した
- Logging ライブラリを作成した
- Logging のテストを作成した
- コントリビュータに向けてライブラリ開発のセットアップ方法を README.md に記述した

# What operation was verified? (なんの動作を確認しましたか?)

- [x] フォーマッタが正しく動作することを確認した
- [x] 静的解析が正しく動作することを確認した
- [x] ライブラリ内容がガイド内容に沿っていることを確認した
- [x] 静的解析の指摘が 0 個であることを確認した
- [x] テストのラインカバレッジが 100% であることを確認した
- [x] テストをすべてパスしたことを確認した

# Message to reviewers (レビュアーへのメッセージ)

- [ ] ガイドに要件と使い方が書かれていますか？
- [ ] ガイドに対応するプロダクションコードと自動テストコードが作成されていますか？
- [ ] README を見てローカルでの開発環境をセットアップできそうですか？
- [ ] コードは読みやすいですか？
- [ ] 他に必要なテスト項目はありますか？

2022-10-12 13:37 UTC, kiyohome requested changes

2022-10-12 13:37 UTC, kiyohome commented on README.md
> +3. `develop` ブランチから任意のブランチを切ります
これはコントリビュータへのメッセージですかね。
ローカル開発とコントリビュータへのメッセージは見出しを分けた方が見やすいと思います。

2022-10-12 13:37 UTC, kiyohome commented on README.md
> +5. `Analyzer` ディレクトリ以下にある `.editorconfig` ファイルをプロジェクトのルートディレクトリ直下に移動します
`.editorconfig` ファイルをAnalyzerに配置している理由はありますか？
リポジトリ直下に置いたらダメでしょうか？

2022-10-12 13:37 UTC, kiyohome commented on README.md
> +1. `External Tools` タブ内の `Generate .csproj files for:` のうち `Embedded packages` にチェックを付けます
はじめから`Embedded packages`にチェック付いてますがこの作業は必要ですか？

2022-10-12 13:37 UTC, kiyohome commented on README.md
> +4. `Analyzer~` ディレクトリを `Analyzer` にリネームします
`Analyzer~`に含まれているdllファイルは私たちが配布してもライセンス違反になりませんか？

2022-10-12 13:37 UTC, kiyohome commented on Analyzer~/Dummy.cs
> +namespace Extreal.Core.Logging.Analyzer
このファイルは必要なんですか？

2022-10-12 13:37 UTC, kiyohome commented on Analyzer~/.editorconfig
> +# EditorConfig is awesome: https://EditorConfig.org
この設定内容はどのような状態ですか？
どこかから持ってきたものですか？
何かのコーディング規約に合わせて設定したものですか？

2022-10-12 13:37 UTC, kiyohome commented on Analyzer~/Extreal.Core.Logging.Analyzer.asmdef
> +    "name": "Extreal.Core.Logging.Analyzer",
アセンブリ定義の内容について教えてください。

2022-10-12 13:37 UTC, kiyohome commented on Runtime/ILogOutputChecker.cs
> +        void SetLogLevel(LogLevel logLevel);
公開APIはドキュメントコメントを書きませんか？

2022-10-12 13:37 UTC, kiyohome commented on Runtime/LogLevel.cs
> +        DEBUG,
DebugではないかとRiderが警告してました。

2022-10-12 13:37 UTC, kiyohome commented on Runtime/LogLevelLogOutputChecker.cs
> +        private bool _isDebug;
falseは明示的に書かないものなんですね。

2022-10-12 13:37 UTC, kiyohome commented on Runtime/Logger.cs
> +            if (_checker.IsDebug(_logCategory))
`IsDebug()`を読んだ方が実装が重複しなくてよいと思いました。

2022-10-12 13:37 UTC, kiyohome commented on Runtime/LoggingManager.cs
> +            return new Logger(logCategory, s_writer, s_checker);
`logCategory`が同じ場合は生成しないで使いまわした方がよいと思います。

2022-10-12 13:37 UTC, kiyohome commented on Runtime/LoggingManager.cs
> +            s_checker.SetLogLevel(logLevel);
`s_checker.SetLogLevel`の呼び出しはprivateメソッドに集約してフィールドの値を使って行うようにした方が読みやすいように感じます。

2022-10-12 13:37 UTC, kiyohome commented on Runtime/UnityDebugLogWriter.cs
> +            Debug.Log($"[{LogLevel.DEBUG}:{logCategory}] {message}");
https://zenn.dev/monry/articles/438f2f78867dec2a59ab
`StringBuilder.Append()`が速いらしいですが上記は最適化されて`StringBuilder.Append()`と変わらなかったりしますか？

2022-10-12 13:37 UTC, kiyohome commented on Tests/ChangeLogLevelTest.cs
> +    public class ChangeLogLevelTest
テストクラスはプロダクションのクラス単位で作ることが多いのですが今はスペック単位ですかね。
どうするか相談させてください。

2022-10-12 13:37 UTC, kiyohome commented on Tests/ChangeLogOutputCheckerTest.cs
> +        private class TestLogOutputChecker : ILogOutputChecker
ガイドの実装例にそのまま使いたいのでクラス名をAppLogOutputCheckerにしてファイルも分けて欲しいです。

2022-10-12 13:37 UTC, kiyohome commented on package.json
> +    "unity": "2020.3",
unityは2021.3ですかね。

2022-10-12 13:37 UTC, kiyohome commented on package.json
> +    "samples": [
samplesはまだないので不要ですかね。

2022-10-12 13:39 UTC, kiyohome requested changes

2022-10-12 13:39 UTC, kiyohome commented on Tests/LogTimeTest.cs
> +                logger.LogDebug("TIMETEST");
`LogLevelLogOutputChecker`の判定処理の時間を気にしてます。

2022-10-13 02:11 UTC, kiyohome requested changes

2022-10-13 02:11 UTC, kiyohome commented on Runtime/Extreal.Core.Logging.asmdef
> +        "Extreal.Core.Logging.Analyzer"
RuntimeにAnalyzerがあるけど必要でしょうか？
ビルドするときにDLLがはいってしまうとかないですか？

2022-10-13 02:20 UTC, sus-taguchi-t commented on README.md
> +3. `develop` ブランチから任意のブランチを切ります
分けて書きます。

2022-10-13 02:21 UTC, sus-taguchi-t commented on README.md
> +5. `Analyzer` ディレクトリ以下にある `.editorconfig` ファイルをプロジェクトのルートディレクトリ直下に移動します
当初はこうしないとアナライザが走らないと思っていました。
リポジトリ直下で動作することを確認したのでそちらに移動しておきます。

2022-10-13 02:22 UTC, sus-taguchi-t commented on README.md
> +1. `External Tools` タブ内の `Generate .csproj files for:` のうち `Embedded packages` にチェックを付けます
必要になります。
アナライザを適用させるためです。

2022-10-13 02:24 UTC, sus-taguchi-t commented on README.md
> +4. `Analyzer~` ディレクトリを `Analyzer` にリネームします
Microsoft を冠するアナライザはすべて MIT ライセンスなので問題ないです。
CodeCracker は Apatch ライセンスですが、不要の可能性があるので調査して導入すべきかを再検討します。

2022-10-13 02:24 UTC, sus-taguchi-t commented on Analyzer~/Dummy.cs
> +namespace Extreal.Core.Logging.Analyzer
必要になります。
アナライザをアセンブリで分けるためです。

2022-10-13 02:26 UTC, sus-taguchi-t commented on Analyzer~/.editorconfig
> +# EditorConfig is awesome: https://EditorConfig.org
Roslyn が提供しているものを導入しました。
細かいところはカスタマイズしています。
主に Unity 開発用にカスタマイズしています。
（使用していないコードを削除する機能をオフにしていたり readonly にできるものを readonly にする機能をオフにしたり）

2022-10-13 02:32 UTC, sus-taguchi-t commented on Analyzer~/Extreal.Core.Logging.Analyzer.asmdef
> +    "name": "Extreal.Core.Logging.Analyzer",
基本的に依存関係を考える最小単位がアセンブリです。
再利用できるものやプロジェクトに導入する際に必要なものをまとめるのがアセンブリ化の考え方です。
参考：  https://ufcpp.net/study/csharp/package/project/

2022-10-13 02:33 UTC, sus-taguchi-t commented on Runtime/ILogOutputChecker.cs
> +        void SetLogLevel(LogLevel logLevel);
書きます。

2022-10-13 02:35 UTC, sus-taguchi-t commented on Runtime/LogLevel.cs
> +        DEBUG,
警告を出していた静的解析の ID を教えていただけると嬉しいです。
PascalCase に統一することも視野に入れましょう。

2022-10-13 02:36 UTC, sus-taguchi-t commented on Runtime/LogLevelLogOutputChecker.cs
> +        private bool _isDebug;
明示的に書きましょう。
静的解析に盲目的に従っていました。
静的解析の提案も切ろうと思います。

2022-10-13 02:36 UTC, sus-taguchi-t commented on Runtime/Logger.cs
> +            if (_checker.IsDebug(_logCategory))
実行時間を計測してみて誤差の範囲であれば変更します。

2022-10-13 02:37 UTC, sus-taguchi-t commented on Runtime/LoggingManager.cs
> +            return new Logger(logCategory, s_writer, s_checker);
その通りだと思います。
Dictionary にして過去に作成した Logger は保存しておくように変更します。

2022-10-13 02:38 UTC, sus-taguchi-t commented on Runtime/LoggingManager.cs
> +            s_checker.SetLogLevel(logLevel);
その通りだと思います。
変更します。

2022-10-13 02:40 UTC, sus-taguchi-t commented on Runtime/UnityDebugLogWriter.cs
> +            Debug.Log($"[{LogLevel.DEBUG}:{logCategory}] {message}");
おそらく `StringBuilder.Append()` の方が圧倒的に速いのでそちらに変更して実行時間計測してみます。

2022-10-13 02:40 UTC, sus-taguchi-t commented on Tests/ChangeLogLevelTest.cs
> +    public class ChangeLogLevelTest
今はスペック単位になっています。
クラス単位に変更します。

2022-10-13 02:41 UTC, sus-taguchi-t commented on Tests/ChangeLogOutputCheckerTest.cs
> +        private class TestLogOutputChecker : ILogOutputChecker
わかりました。
更新しておきます。

2022-10-13 02:41 UTC, sus-taguchi-t commented on package.json
> +    "unity": "2020.3",
はい、そうです。
更新しておきます。

2022-10-13 02:41 UTC, sus-taguchi-t commented on package.json
> +    "samples": [
そうです。
更新しておきます。

2022-10-13 02:42 UTC, sus-taguchi-t commented on Tests/LogTimeTest.cs
> +                logger.LogDebug("TIMETEST");
判定処理のみの時間を図るように変更します。

2022-10-13 02:44 UTC, sus-taguchi-t commented on Runtime/Extreal.Core.Logging.asmdef
> +        "Extreal.Core.Logging.Analyzer"
調査してみます。
DLL が入ってしまうようでしたら README のローカル開発で導入してもらう方針に変更します。

2022-10-13 07:29 UTC, sus-taguchi-t commented on Runtime/UnityDebugLogWriter.cs
> +            Debug.Log($"[{LogLevel.DEBUG}:{logCategory}] {message}");
実行時間がほとんど変わらなかったので変更はなしにしました。

2022-10-14 00:19 UTC, sus-taguchi-t commented on README.md
> +3. `develop` ブランチから任意のブランチを切ります
変更しました。
https://github.com/extreal-dev/Extreal.Core.Logging/pull/2/commits/e9bbfe3463c5561934788ef51afb1249a00fe57c

2022-10-14 00:21 UTC, sus-taguchi-t commented on README.md
> +5. `Analyzer` ディレクトリ以下にある `.editorconfig` ファイルをプロジェクトのルートディレクトリ直下に移動します
変更しました。
https://github.com/extreal-dev/Extreal.Core.Logging/pull/2/commits/efb5b48b8bf5e360199f903143197a453db5f614
https://github.com/extreal-dev/Extreal.Core.Logging/pull/2/commits/e1e1ae8811959bc58a9ec67888ca924cd4ac06eb

2022-10-14 00:22 UTC, sus-taguchi-t commented on Analyzer~/Dummy.cs
> +namespace Extreal.Core.Logging.Analyzer
変更しました。
https://github.com/extreal-dev/Extreal.Core.Logging/pull/2/commits/e1592501c819d5cf707edbb4b2e471ac709f84ac

2022-10-14 00:23 UTC, sus-taguchi-t commented on Tests/ChangeLogLevelTest.cs
> +    public class ChangeLogLevelTest
変更しました。
https://github.com/extreal-dev/Extreal.Core.Logging/pull/2/commits/8f232d7671ce2e4041fb37ce456b7cd91d854fcd

2022-10-14 00:24 UTC, sus-taguchi-t commented on Runtime/LogLevelLogOutputChecker.cs
> +        private bool _isDebug;
変更しました。
https://github.com/extreal-dev/Extreal.Core.Logging/pull/2/commits/47fbb4f3774b1721515614242a91e97967d85ec4
https://github.com/extreal-dev/Extreal.Core.Logging/pull/2/commits/efb5b48b8bf5e360199f903143197a453db5f614
https://github.com/extreal-dev/Extreal.Core.Logging/pull/2/commits/e1e1ae8811959bc58a9ec67888ca924cd4ac06eb

2022-10-14 00:26 UTC, sus-taguchi-t commented on Runtime/Logger.cs
> +            if (_checker.IsDebug(_logCategory))
変更しました。
https://github.com/extreal-dev/Extreal.Core.Logging/pull/2/commits/6aa51c22e9860061ea461af9a924273cd3ce7f59

2022-10-14 00:27 UTC, sus-taguchi-t commented on Runtime/LoggingManager.cs
> +            return new Logger(logCategory, s_writer, s_checker);
変更しました。
https://github.com/extreal-dev/Extreal.Core.Logging/pull/2/commits/9944bbb978a80f407425276da3d1afd256671a1b

2022-10-14 00:27 UTC, sus-taguchi-t commented on Runtime/LoggingManager.cs
> +            s_checker.SetLogLevel(logLevel);
変更しました。
https://github.com/extreal-dev/Extreal.Core.Logging/pull/2/commits/9944bbb978a80f407425276da3d1afd256671a1b

2022-10-14 00:28 UTC, sus-taguchi-t commented on Tests/ChangeLogOutputCheckerTest.cs
> +        private class TestLogOutputChecker : ILogOutputChecker
変更しました。
https://github.com/extreal-dev/Extreal.Core.Logging/pull/2/commits/8f232d7671ce2e4041fb37ce456b7cd91d854fcd

2022-10-14 00:29 UTC, sus-taguchi-t commented on package.json
> +    "unity": "2020.3",
変更しました。
https://github.com/extreal-dev/Extreal.Core.Logging/pull/2/commits/4778d2143626b82499480e5236377dee3782a167

2022-10-14 00:30 UTC, sus-taguchi-t commented on package.json
> +    "samples": [
変更しました。
https://github.com/extreal-dev/Extreal.Core.Logging/pull/2/commits/4778d2143626b82499480e5236377dee3782a167

2022-10-14 00:31 UTC, sus-taguchi-t commented on Tests/LogTimeTest.cs
> +                logger.LogDebug("TIMETEST");
変更しました。
https://github.com/extreal-dev/Extreal.Core.Logging/pull/2/commits/8f232d7671ce2e4041fb37ce456b7cd91d854fcd

2022-10-14 00:32 UTC, sus-taguchi-t commented on Runtime/Extreal.Core.Logging.asmdef
> +        "Extreal.Core.Logging.Analyzer"
変更しました。
https://github.com/extreal-dev/Extreal.Core.Logging/pull/2/commits/15a487d7527082acac418f2548c6bb4705214ad1
https://github.com/extreal-dev/Extreal.Core.Logging/pull/2/commits/e9bbfe3463c5561934788ef51afb1249a00fe57c

2022-10-14 03:00 UTC, sus-taguchi-t commented on README.md
> +4. `Analyzer~` ディレクトリを `Analyzer` にリネームします
Analyzer のタスクに記載しました。

2022-10-14 03:11 UTC, sus-taguchi-t commented on Runtime/LogLevel.cs
> +        DEBUG,
PascalCase に変更しました。
https://github.com/extreal-dev/Extreal.Core.Logging/pull/2/commits/df756eb22eb5e86470a2e1ce2eac858f4deb2bdd

2022-10-14 03:30 UTC, sus-taguchi-t commented on Runtime/UnityDebugLogWriter.cs
> +            Debug.Log($"[{LogLevel.DEBUG}:{logCategory}] {message}");
平均 10 ns 程度しか変わらないが、利用者に最適化していることが見えるように変更しました。
https://github.com/extreal-dev/Extreal.Core.Logging/pull/2/commits/082d37755ab1a62c044f9b9a39b34c1be2fc4c9b

2022-10-14 05:11 UTC, sus-taguchi-t commented on Runtime/LoggingManager.cs
> +            return new Logger(logCategory, s_writer, s_checker);
併せて初期化の処理を変更しました。
https://github.com/extreal-dev/Extreal.Core.Logging/pull/2/commits/5ccacaed669fe7a6000a54d663aeb50c750b7617

2022-10-14 05:12 UTC, sus-taguchi-t commented on Runtime/LoggingManager.cs
> +            s_checker.SetLogLevel(logLevel);
初期化処理の変更に際して private な `SetLogLevel` メソッドが不要になったので削除しました。
https://github.com/extreal-dev/Extreal.Core.Logging/pull/2/commits/5ccacaed669fe7a6000a54d663aeb50c750b7617

2022-10-14 05:13 UTC, sus-taguchi-t commented
Test 用の Utility のアセンブリを分けました。
https://github.com/extreal-dev/Extreal.Core.Logging/pull/2/commits/ee3a7d9c66d7a1b90518c12a2a30676044038bff

2022-10-17 03:03 UTC, sus-taguchi-t commented on Runtime/ILogOutputChecker.cs
> +        void SetLogLevel(LogLevel logLevel);
書きました。
https://github.com/extreal-dev/Extreal.Core.Logging/pull/2/commits/80064476bdcc94eaafd8cb8e6894f5779179f1d5

2022-10-17 06:07 UTC, sus-taguchi-t commented
`Logger` クラスが `UnityEngine` にも `Extreal.Core.Logging` にもあって使用する際に曖昧な参照になるので、やはりクラス名は何かしら変えた方がいいと思います。

2022-10-17 23:03 UTC, kiyohome commented on README.md
> +3. `develop` ブランチから任意のブランチを切ります
LGTM

2022-10-17 23:04 UTC, kiyohome commented on README.md
> +5. `Analyzer` ディレクトリ以下にある `.editorconfig` ファイルをプロジェクトのルートディレクトリ直下に移動します
LGTM

2022-10-17 23:05 UTC, kiyohome commented on README.md
> +1. `External Tools` タブ内の `Generate .csproj files for:` のうち `Embedded packages` にチェックを付けます
LGTM

2022-10-17 23:05 UTC, kiyohome commented on README.md
> +4. `Analyzer~` ディレクトリを `Analyzer` にリネームします
LGTM

2022-10-17 23:05 UTC, kiyohome commented on Analyzer~/Dummy.cs
> +namespace Extreal.Core.Logging.Analyzer
LGTM

2022-10-17 23:07 UTC, kiyohome commented on Runtime/UnityDebugLogWriter.cs
> +            Debug.Log($"[{LogLevel.DEBUG}:{logCategory}] {message}");
LGTM

2022-10-18 00:13 UTC, kiyohome requested changes

2022-10-18 00:13 UTC, kiyohome commented on Tests/Tests.asmdef
> +    "rootNamespace": "",
`rootNamespace`は指定しませんか？
https://docs.unity3d.com/ja/2021.1/Manual/class-AssemblyDefinitionImporter.html
この指定があって一致していると何もでないんですが。
![image](https://user-images.githubusercontent.com/13113214/196300445-95fb52f8-f256-412e-8f51-d8e681172414.png)

2022-10-18 00:13 UTC, kiyohome commented on Tests/LogOutputChekerTest.cs
> +    public class LogOutputChekerTest
クラス名がタイポしてます。
LogOutputChekerTest
LogOutputCheckerTest

2022-10-18 00:13 UTC, kiyohome commented on Tests/AppLogWriter.cs
> +            Debug.Log($"(o-o) {logCategory}: {message}");
こちらもprivateメソッドにフォーマット処理を切り出して、StringBuilderを使う実装にしておきましょう。ガイドに載せてソースはコピペされることが多いです。

2022-10-18 00:13 UTC, kiyohome commented on Runtime/ILogOutputChecker.cs
> +        void SetLogLevel(LogLevel logLevel);
LoggingManagerと合わせてこちらもinitializeにメソッド名を変えて初期化と分かるようにした方がいいと思います。

2022-10-18 00:13 UTC, kiyohome commented on Runtime/ILogOutputChecker.cs
> +        /// Checks if infomation logs are output.
タイポ
infomation

2022-10-18 00:13 UTC, kiyohome commented on Runtime/ILogOutputChecker.cs
> +        /// Checks if infomation logs are output.
ILogWriterにもあります。
全体的に検索してください。

2022-10-18 00:13 UTC, kiyohome commented on Runtime/Logger.cs
> +        public Logger(
LoggingManagerしか生成しないのであればpublicでなくてよいと思います。

2022-10-18 00:13 UTC, kiyohome commented on Runtime/Logger.cs
> +    /// Class for handling logs.
クラスの全体的な話しとしてログ出力判定とログ書き込みをILogOutputCheckerとILogWriterに移譲していること、ログ出力メソッドが判定してから出力することを書いておいてもよいかと思いました。
各ログ出力メソッドに出力有無を判定してから出すと書くのは重複すると思ったのでクラスのとこにまとめて説明がいいかと思いました。

2022-10-18 00:13 UTC, kiyohome commented on Runtime/LogLevelLogOutputChecker.cs
> +    /// Class used as default to check if logs should be ouput.
タイポ
ouput

2022-10-18 00:13 UTC, kiyohome commented on Tests/LoggingManagerTest.cs
> +            var logger = LoggingManager.GetLogger(LOG_CATEGORY);
全体的な話しです。
stringやExceptionなど引数にnullが指定された場合のテストケースを入れて欲しいです。
nullが指定された場合に意図した通り動くことを確認するテストです。
どこかで実行時例外が出るとFWの実装を知らない人がデバッグしないといけなくなるので事前にFW開発側でテストしておきたいです。

2022-10-18 00:13 UTC, kiyohome commented on Tests/ChangeLogLevelTest.cs
> +    public class ChangeLogLevelTest
LGTM

2022-10-18 00:14 UTC, kiyohome commented on package.json
> +    "unity": "2020.3",
LGTM

2022-10-18 00:14 UTC, kiyohome commented on package.json
> +    "samples": [
LGTM

2022-10-18 00:14 UTC, kiyohome commented on Tests/LogTimeTest.cs
> +                logger.LogDebug("TIMETEST");
LGTM

2022-10-18 00:15 UTC, kiyohome commented on Runtime/Extreal.Core.Logging.asmdef
> +        "Extreal.Core.Logging.Analyzer"
LGTM

2022-10-18 00:21 UTC, sus-taguchi-t commented on Tests/Tests.asmdef
> +    "rootNamespace": "",
加えましょう。

2022-10-18 00:22 UTC, sus-taguchi-t commented on Tests/LogOutputChekerTest.cs
> +    public class LogOutputChekerTest
すみません、ありがとうございます。
直します。

2022-10-18 00:22 UTC, sus-taguchi-t commented on Tests/AppLogWriter.cs
> +            Debug.Log($"(o-o) {logCategory}: {message}");
分かりました。
直しておきます。

2022-10-18 00:24 UTC, sus-taguchi-t commented on Runtime/ILogOutputChecker.cs
> +        void SetLogLevel(LogLevel logLevel);
確かにその通りだと思います。
直しておきます。

2022-10-18 00:24 UTC, sus-taguchi-t commented on Runtime/ILogOutputChecker.cs
> +        /// Checks if infomation logs are output.
すみません、ありがとうございます。
直しておきます。

2022-10-18 00:26 UTC, sus-taguchi-t commented on Runtime/Logger.cs
> +        public Logger(
`internal` でいいですね。
直しておきます。

2022-10-18 00:29 UTC, sus-taguchi-t commented on Runtime/Logger.cs
> +    /// Class for handling logs.
実はそれは載せるか迷ってはいました。
載せておきます。

2022-10-18 00:29 UTC, sus-taguchi-t commented on Runtime/LogLevelLogOutputChecker.cs
> +    /// Class used as default to check if logs should be ouput.
すみません、ありがとうございます。
直しておきます。

2022-10-18 00:31 UTC, sus-taguchi-t commented on Tests/LoggingManagerTest.cs
> +            var logger = LoggingManager.GetLogger(LOG_CATEGORY);
分かりました。
しかし `null` が入ってくることは全体的にあまり意図していないので、どのような挙動が想定通りなのかは相談させて下さい。

2022-10-18 00:41 UTC, sus-taguchi-t commented on Tests/Tests.asmdef
> +    "rootNamespace": "",
変更しました。
https://github.com/extreal-dev/Extreal.Core.Logging/pull/2/commits/3b8cac8b80a94b0e7c6eed4df7e27669d1a9040e

2022-10-18 00:53 UTC, sus-taguchi-t commented on Tests/AppLogWriter.cs
> +            Debug.Log($"(o-o) {logCategory}: {message}");
変更しました。
https://github.com/extreal-dev/Extreal.Core.Logging/pull/2/commits/57f83f1d133406dd10a33ef6f9d6215f20657b70

2022-10-18 05:09 UTC, sus-taguchi-t commented on Runtime/ILogOutputChecker.cs
> +        void SetLogLevel(LogLevel logLevel);
変更しました。
https://github.com/extreal-dev/Extreal.Core.Logging/pull/2/commits/f0c058f73efb3888d0fe38accc23c38f2f7c79ae

2022-10-18 05:16 UTC, sus-taguchi-t commented on Runtime/Logger.cs
> +        public Logger(
変更しました。
https://github.com/extreal-dev/Extreal.Core.Logging/pull/2/commits/866edb5d42bd4e56c2ba96b2c23208c734fd583b

2022-10-18 05:25 UTC, sus-taguchi-t commented on Tests/LogOutputChekerTest.cs
> +    public class LogOutputChekerTest
修正しました。
https://github.com/extreal-dev/Extreal.Core.Logging/pull/2/commits/1c73211aa43545c686b48986152a95eee6770759

2022-10-18 05:25 UTC, sus-taguchi-t commented on Runtime/ILogOutputChecker.cs
> +        /// Checks if infomation logs are output.
修正しました。
https://github.com/extreal-dev/Extreal.Core.Logging/pull/2/commits/1c73211aa43545c686b48986152a95eee6770759

2022-10-18 05:25 UTC, sus-taguchi-t commented on Runtime/LogLevelLogOutputChecker.cs
> +    /// Class used as default to check if logs should be ouput.
修正しました。
https://github.com/extreal-dev/Extreal.Core.Logging/pull/2/commits/1c73211aa43545c686b48986152a95eee6770759

2022-10-18 05:43 UTC, sus-taguchi-t commented on Runtime/Logger.cs
> +    /// Class for handling logs.
修正しました。
https://github.com/extreal-dev/Extreal.Core.Logging/pull/2/commits/ea7ab49d04705908b36bbb3c850f8fd29e517f5a

2022-10-18 06:32 UTC, sus-taguchi-t commented on Tests/LoggingManagerTest.cs
> +            var logger = LoggingManager.GetLogger(LOG_CATEGORY);
作成しました。
https://github.com/extreal-dev/Extreal.Core.Logging/pull/2/commits/ddfb316646c8e9ceded8897c85ef0265283179bf

2022-10-18 08:04 UTC, kiyohome commented on Tests/ChangeLogOutputCheckerTest.cs
> +        private class TestLogOutputChecker : ILogOutputChecker
LGTM

2022-10-18 08:10 UTC, kiyohome commented on Tests/Tests.asmdef
> +    "rootNamespace": "",
まだRiderから警告が出てました。
https://docs.unity3d.com/ja/2021.3/Manual/cus-layout.html
Testsの下にRuntimeが必要なんですかね？

2022-10-18 08:21 UTC, kiyohome commented on Tests/LogOutputChekerTest.cs
> +    public class LogOutputChekerTest
ファイル名が直ってないようです。

2022-10-18 08:26 UTC, kiyohome commented on Tests/AppLogWriter.cs
> +            Debug.Log($"(o-o) {logCategory}: {message}");
LGTM

2022-10-18 08:30 UTC, kiyohome commented on Runtime/ILogOutputChecker.cs
> +        void SetLogLevel(LogLevel logLevel);
LGTM

2022-10-18 08:31 UTC, kiyohome commented on Runtime/ILogOutputChecker.cs
> +        /// Checks if infomation logs are output.
LGTM

2022-10-18 08:32 UTC, kiyohome commented on Runtime/Logger.cs
> +        public Logger(
LGTM

2022-10-18 08:32 UTC, kiyohome commented on Runtime/Logger.cs
> +    /// Class for handling logs.
LGTM

2022-10-18 08:33 UTC, kiyohome commented on Runtime/LogLevelLogOutputChecker.cs
> +    /// Class used as default to check if logs should be ouput.
LGTM

2022-10-18 08:41 UTC, kiyohome commented on Tests/LoggingManagerTest.cs
> +            var logger = LoggingManager.GetLogger(LOG_CATEGORY);
LGTM

2022-10-19 01:40 UTC, kiyohome commented on Analyzer~/.editorconfig
> +# EditorConfig is awesome: https://EditorConfig.org
LGTM

2022-10-19 01:40 UTC, kiyohome commented on Analyzer~/Extreal.Core.Logging.Analyzer.asmdef
> +    "name": "Extreal.Core.Logging.Analyzer",
LGTM

2022-10-19 01:41 UTC, kiyohome commented on Runtime/ILogOutputChecker.cs
> +        void SetLogLevel(LogLevel logLevel);
LGTM

2022-10-19 01:41 UTC, kiyohome commented on Runtime/LogLevel.cs
> +        DEBUG,
LGTM

2022-10-19 01:41 UTC, kiyohome commented on Runtime/LogLevelLogOutputChecker.cs
> +        private bool _isDebug;
LGTM

2022-10-19 01:42 UTC, kiyohome commented on Runtime/Logger.cs
> +            if (_checker.IsDebug(_logCategory))
LGTM

2022-10-19 01:43 UTC, kiyohome commented on Runtime/LoggingManager.cs
> +            return new Logger(logCategory, s_writer, s_checker);
LGTM

2022-10-19 01:43 UTC, kiyohome commented on Runtime/LoggingManager.cs
> +            s_checker.SetLogLevel(logLevel);
LGTM

2022-10-19 01:49 UTC, kiyohome requested changes

2022-10-19 01:49 UTC, kiyohome commented on Runtime/ILogWriter.cs
> +    /// Interface for implementation how to log.
Checker、WriterのIFはmain処理を止めないために例外を出してはいけないことをドキュメンテーションコメントに追記しときましょう。

2022-10-19 01:49 UTC, kiyohome commented on Runtime/Logger.cs
> +            if (IsDebug())
Checker、Writerの呼び出しは防御的措置として例外をキャッチしUnity.Debuggerで出してmain処理を継続できるようにしましょう。ログは出さないことになります。
Loggerのドキュメンテーションコメントに例外発生時の動作を書いておいて欲しいです。

2022-10-19 01:49 UTC, kiyohome commented on Runtime/ILogWriter.cs
> +        void LogDebug(string logCategory, string message);
性能的に問題なければChecker、Writerのメソッドは分けない方がいいと思いました。

2022-10-19 02:07 UTC, sus-taguchi-t commented on Tests/Tests.asmdef
> +    "rootNamespace": "",
Runtime を作成してファイルを移動しました。
https://github.com/extreal-dev/Extreal.Core.Logging/pull/2/commits/d3ea91bc778f08dcca78bcd662ca194aa3014871

2022-10-19 02:10 UTC, sus-taguchi-t commented on Tests/LogOutputChekerTest.cs
> +    public class LogOutputChekerTest
すみません。
修正しました。
https://github.com/extreal-dev/Extreal.Core.Logging/pull/2/commits/ada7b1745e3ee7f30bb2214fe688224bba6662e4

2022-10-19 07:00 UTC, sus-taguchi-t commented on Runtime/ILogWriter.cs
> +    /// Interface for implementation how to log.
追記しました。
https://github.com/extreal-dev/Extreal.Core.Logging/pull/2/commits/08499c81956486fe2e8dda9eee5e5186af2b418c

2022-10-19 07:01 UTC, sus-taguchi-t commented on Runtime/Logger.cs
> +            if (IsDebug())
防御的措置を導入し、ドキュメンテーションコメントを追記しました。
https://github.com/extreal-dev/Extreal.Core.Logging/pull/2/commits/08499c81956486fe2e8dda9eee5e5186af2b418c

2022-10-19 07:02 UTC, sus-taguchi-t commented on Runtime/ILogWriter.cs
> +        void LogDebug(string logCategory, string message);
それぞれ 1 つのメソッドで動作するように変更しました。
性能的には平均 1 ns 以内の誤差です。
https://github.com/extreal-dev/Extreal.Core.Logging/pull/2/commits/08499c81956486fe2e8dda9eee5e5186af2b418c

2022-10-19 07:44 UTC, kiyohome commented on Tests/Tests.asmdef
> +    "rootNamespace": "",
LGTM

2022-10-19 08:36 UTC, kiyohome commented on Runtime/UnityDebugLogWriter.cs
> +                    Debug.LogException(new Exception("Undefined LogLevel was input"));
これが発生するのはFW開発者がLogLevelを追加して実装をもらした場合になりませんか？
そうであれば実行時例外を投げて気づけるようにした方がよいと思います。

2022-10-19 08:36 UTC, kiyohome commented on Runtime/UnityDebugLogWriter.cs
> +                    Debug.LogException(new Exception("Undefined LogLevel was input"));
AppLogWriterのswitch文も同じです。

2022-10-19 08:36 UTC, kiyohome commented on Tests/LogOutputChekerTest.cs
> +    public class LogOutputChekerTest
LGTM

2022-10-19 08:36 UTC, kiyohome commented on Runtime/ILogWriter.cs
> +    /// Interface for implementation how to log.
LGTM

2022-10-19 08:37 UTC, kiyohome commented on Runtime/Logger.cs
> +            if (IsDebug())
LGTM

2022-10-19 08:38 UTC, kiyohome commented on Runtime/ILogWriter.cs
> +        void LogDebug(string logCategory, string message);
LGTM

2022-10-19 08:42 UTC, kiyohome requested changes

2022-10-19 08:42 UTC, kiyohome commented on Tests/Runtime/Extreal.Core.LoggingTest.asmdef
> +{
ファイル名のLoggingTestの間にドットが入ってないです。

2022-10-19 08:53 UTC, sus-taguchi-t commented on Runtime/UnityDebugLogWriter.cs
> +                    Debug.LogException(new Exception("Undefined LogLevel was input"));
https://github.com/extreal-dev/Extreal.Core.Logging/blob/08499c81956486fe2e8dda9eee5e5186af2b418c/Tests/Runtime/ELoggerTest.cs#L85-L89
テストコードを見ていただければ実例がありますが、`LogLevel` を追加しなくてもユーザ側でこの `defaut` 節に入るコードは書けてしまいます。
それでも実行時例外を投げさせた方が良いでしょうか。

2022-10-19 09:05 UTC, sus-taguchi-t commented on Tests/Runtime/Extreal.Core.LoggingTest.asmdef
> +{
すみません。
修正しました。
https://github.com/extreal-dev/Extreal.Core.Logging/pull/2/commits/b46418c4992a28c19e4c0aebdcf7414124affe91

2022-10-19 23:02 UTC, kiyohome commented on Runtime/UnityDebugLogWriter.cs
> +                    Debug.LogException(new Exception("Undefined LogLevel was input"));
テストコードは見てましたが、テストのためのコードと思ってました。
アプリ開発者が`Enum.Parse`を使った場合も私たちとしては想定していない使い方（実装不備）であれば実行時例外で開発中に気づけるべきと思います。

2022-10-19 23:19 UTC, kiyohome requested changes

2022-10-19 23:19 UTC, kiyohome commented on Runtime/ILogWriter.cs
> +        void Log(LogLevel logLevel, string logCategory, string message, Exception exception);
`exception = null`にはしないものですか？

2022-10-19 23:47 UTC, kiyohome requested changes

2022-10-19 23:47 UTC, kiyohome commented on Runtime/LoggingManager.cs
> +            s_checker = checker ?? new LogLevelLogOutputChecker();
staticフィールドの宣言時に初期化しているので下記だとダメですかね？
```
s_checker = checker ?? s_checker;
```

2022-10-20 00:15 UTC, sus-taguchi-t commented on Runtime/UnityDebugLogWriter.cs
> +                    Debug.LogException(new Exception("Undefined LogLevel was input"));
`Enum.Parse` は想定しない方針で良いかと思うので、実行時例外に変えておきます！

2022-10-20 00:23 UTC, sus-taguchi-t commented on Runtime/ILogWriter.cs
> +        void Log(LogLevel logLevel, string logCategory, string message, Exception exception);
実装に自由度を持たせようとして指定していませんでした。
しかし `exception` は基本的になしで使うことが想定だと思うので、`exception = null` にしておきます。

2022-10-20 00:26 UTC, sus-taguchi-t commented on Runtime/LoggingManager.cs
> +            s_checker = checker ?? new LogLevelLogOutputChecker();
確かに初期化なので、途中でこの処理を挟まないという前提条件下であればその文で大丈夫だと思います。
変更しておきます。

2022-10-20 00:42 UTC, sus-taguchi-t commented on Runtime/UnityDebugLogWriter.cs
> +                    Debug.LogException(new Exception("Undefined LogLevel was input"));
変更しました。
https://github.com/extreal-dev/Extreal.Core.Logging/pull/2/commits/9d959c3854034979a8c06d43d44e3bca91f2a165

2022-10-20 00:54 UTC, sus-taguchi-t commented on Runtime/ILogWriter.cs
> +        void Log(LogLevel logLevel, string logCategory, string message, Exception exception);
変更しました。
https://github.com/extreal-dev/Extreal.Core.Logging/pull/2/commits/4541a1978f4b1880008617028249ead1788d8d38

2022-10-20 01:02 UTC, sus-taguchi-t commented on Runtime/LoggingManager.cs
> +            s_checker = checker ?? new LogLevelLogOutputChecker();
変更しました。
https://github.com/extreal-dev/Extreal.Core.Logging/pull/2/commits/50dbe138a63f7e9e938416e949dfd6467b19f8d4

2022-10-20 01:22 UTC, kiyohome requested changes

2022-10-20 01:22 UTC, kiyohome commented on Runtime/ELogger.cs
> +        public void Log(LogLevel logLevel, string message, Exception exception = null)
ELoggerはログレベルごとにメソッドを用意しましょう。可読性が落ちているように感じました。

2022-10-20 03:53 UTC, kiyohome commented on Runtime/UnityDebugLogWriter.cs
> +                    Debug.LogException(new Exception("Undefined LogLevel was input"));
NotSupportedExceptionの方がよくないでしょうか？

2022-10-20 03:53 UTC, kiyohome commented on Tests/Runtime/Extreal.Core.LoggingTest.asmdef
> +{
LGTM

2022-10-20 03:54 UTC, kiyohome commented on Runtime/ILogWriter.cs
> +        void Log(LogLevel logLevel, string logCategory, string message, Exception exception);
LGTM

2022-10-20 03:56 UTC, kiyohome commented on Runtime/LoggingManager.cs
> +            s_checker = checker ?? new LogLevelLogOutputChecker();
LGTM

2022-10-20 04:36 UTC, sus-taguchi-t commented on Runtime/UnityDebugLogWriter.cs
> +                    Debug.LogException(new Exception("Undefined LogLevel was input"));
意味合いとしては `ArgumentOutOfRangeException` の方が近いため、こちらで実装が良いと思います。

2022-10-20 04:37 UTC, sus-taguchi-t commented on Runtime/ELogger.cs
> +        public void Log(LogLevel logLevel, string message, Exception exception = null)
同感です。
修正します。

2022-10-20 04:37 UTC, sus-taguchi-t commented on Runtime/ELogger.cs
> +        public void Log(LogLevel logLevel, string message, Exception exception = null)
修正しました！
https://github.com/extreal-dev/Extreal.Core.Logging/pull/2/commits/b30320bb27d07dc7a2943ec0c14503a9ac37d867

2022-10-20 07:30 UTC, kiyohome commented on Runtime/UnityDebugLogWriter.cs
> +                    Debug.LogException(new Exception("Undefined LogLevel was input"));
いいと思います！

2022-10-20 07:32 UTC, kiyohome commented on Runtime/ELogger.cs
> +        public void Log(LogLevel logLevel, string message, Exception exception = null)
LGTM

2022-10-20 07:36 UTC, sus-taguchi-t commented on Runtime/UnityDebugLogWriter.cs
> +                    Debug.LogException(new Exception("Undefined LogLevel was input"));
変更しました！
https://github.com/extreal-dev/Extreal.Core.Logging/pull/2/commits/3179fa2f614e41dceb4949d5c35922687bf920d2

2022-10-20 08:45 UTC, kiyohome commented on Runtime/UnityDebugLogWriter.cs
> +                    Debug.LogException(new Exception("Undefined LogLevel was input"));
LGTM

2022-10-20 08:59 UTC, kiyohome commented on Runtime/UnityDebugLogWriter.cs
> +                    Debug.LogException(new Exception("Undefined LogLevel was input"));
一度いいと思ったんですがRiderが教えてくれました。
https://learn.microsoft.com/ja-jp/dotnet/api/system.argumentoutofrangeexception?view=net-6.0#examples
パラメータ名とメッセージを渡すみたいです。
```
throw new ArgumentOutOfRangeException(nameof(age), $"All guests must be {minimumRequiredAge}-years-old or older.");
```
今の実装だとパラメータ名にメッセージが渡ってます。

2022-10-20 09:02 UTC, kiyohome requested changes

2022-10-20 09:02 UTC, kiyohome commented on Runtime/LoggingManager.cs
> +        private static Dictionary<string, ELogger> s_loggers = new Dictionary<string, ELogger>();
readonlyでよさそうです。

2022-10-21 00:12 UTC, sus-taguchi-t commented on Runtime/UnityDebugLogWriter.cs
> +                    Debug.LogException(new Exception("Undefined LogLevel was input"));
すみません、ありがとうございます。
修正しました。
https://github.com/extreal-dev/Extreal.Core.Logging/pull/2/commits/e26d80b4aff7a47dc11086c0c32642a5917163d3

2022-10-21 00:16 UTC, sus-taguchi-t commented on Runtime/LoggingManager.cs
> +        private static Dictionary<string, ELogger> s_loggers = new Dictionary<string, ELogger>();
変更しました。
https://github.com/extreal-dev/Extreal.Core.Logging/pull/2/commits/e26d80b4aff7a47dc11086c0c32642a5917163d3

2022-10-21 06:11 UTC, kiyohome requested changes

2022-10-21 06:11 UTC, kiyohome commented on Tests/Runtime/Utility/UnityDebugTestUtil.cs
> +namespace Extreal.Core.Logging.Test
アセンブリに合わせてUtilityを付けた方がいいと思いました。

2022-10-21 06:29 UTC, sus-taguchi-t commented on Tests/Runtime/Utility/UnityDebugTestUtil.cs
> +namespace Extreal.Core.Logging.Test
完全に忘れてました……。
直します。

2022-10-21 06:29 UTC, sus-taguchi-t commented on Tests/Runtime/Utility/UnityDebugTestUtil.cs
> +namespace Extreal.Core.Logging.Test
修正しました！
https://github.com/extreal-dev/Extreal.Core.Logging/pull/2/commits/136cea44d0f8f18acff2815f346c0d4dd60fe545

2022-10-21 06:32 UTC, kiyohome commented on Tests/Runtime/Utility/UnityDebugTestUtil.cs
> +namespace Extreal.Core.Logging.Test
LGTM

2022-10-21 06:32 UTC, kiyohome commented on Runtime/LoggingManager.cs
> +        private static Dictionary<string, ELogger> s_loggers = new Dictionary<string, ELogger>();
LGTM

2022-10-21 06:33 UTC, kiyohome commented on Runtime/UnityDebugLogWriter.cs
> +                    Debug.LogException(new Exception("Undefined LogLevel was input"));
LGTM

2022-10-21 11:23 UTC, kiyohome approved these changes

2022-10-21 11:24 UTC, merged